# Generated by Django 4.0.3 on 2022-04-01 03:46

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_context', cloudinary.models.CloudinaryField(max_length=255, verbose_name='thumbnail')),
                ('project_name', models.CharField(max_length=225, unique=True)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('project_category', models.IntegerField(choices=[(0, 'Work'), (1, 'Personal')], default=0)),
                ('role_in_project', models.CharField(max_length=225)),
                ('project_url', models.URLField(max_length=225, unique=True)),
                ('project_description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=225)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, verbose_name='thumbnail')),
                ('meta_description', models.CharField(blank=True, max_length=225)),
                ('content', ckeditor.fields.RichTextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='core.tag')),
            ],
            options={
                'ordering': ['-date_published'],
            },
        ),
    ]
