# Generated by Django 4.0.3 on 2022-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kindword_remove_project_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=225),
        ),
    ]
