# Generated by Django 4.0.3 on 2022-04-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_github_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subtitle',
        ),
    ]
